name = "Overly Optimized"
author = "Cartrigger"
version = "B0.3.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "63a3f2be6129cedaea1a494fdfc8ef9d3ecd42551e5b08b380b980c14e20e0df"

[versions]
fabric = "0.15.11"
minecraft = "1.21"
