name = "Overly Optimized"
author = "Cartrigger"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c64fb145bc6544e36ee4fa4a41d69c3a60c75229b634c709de9afc0cb1e6f18f"

[versions]
fabric = "0.16.7"
minecraft = "1.21.2"
