name = "Overly Optimized"
author = "Cartrigger"
version = "1.0.3"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "1d14123e16eeeefd42a942b7253fd240ddedba7edbff4d8379c2313a4f508532"

[versions]
fabric = "0.15.11"
minecraft = "1.20.6"
