name = "Overly Optimized"
author = "Cartrigger"
version = "1.0.4"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b718fe770c4fd0741986f3bd1480d600186ed90601cae6b1d6d53baa81b32629"

[versions]
fabric = "0.16.0"
minecraft = "1.21.1"
