name = "Overly Optimized"
author = "Cartrigger"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "3902ceaf5a3afaca44e12e0e588cb7ffb98e313336132d6141859a080ab955ab"

[versions]
fabric = "0.16.7"
minecraft = "1.21.3"

[options]
acceptable-game-versions = ["1.21.2"]
