name = "Overly Optimized"
author = "Cartrigger"
version = "4.2.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "8ad3e9c66121a3ceaa63be47ba0e9f03d2373b807448deb475fd85f6627b3850"

[versions]
fabric = "0.15.11"
minecraft = "1.20.1"

[options]
acceptable-game-versions = ["1.20"]
