name = "NeoOVOP"
author = "Cartrigger"
version = "0.0.3"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "5f6fad9f721ef029306eb3e67fa78a8a633da987273232acf9c590e3df4237e0"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.56"
