name = "NeoOVOP"
author = "Cartrigger"
version = "0.0.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b03aecfdaec4947e2233e30c882c8b2f9d83913a6439bb321db9137523f1b5fe"

[versions]
minecraft = "1.21"
neoforge = "21.0.167"
