name: Modrinth Upload For OVOP
# Under ARR, do not copy!
on:
  workflow_dispatch:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Make packwiz executable
        run: |
          chmod +x packwiz
          ls
          chmod +w Modrinth

      - name: Determine Latest Version
        id: determine_version
        run: |
          cd Modrinth
          cd Fabric
          LATEST_VERSION=$(ls -d v* | sort -V | tail -n 1)
          echo "Latest is: $LATEST_VERSION"
          echo "LATEST_VERSION=$LATEST_VERSION" >> $GITHUB_ENV

      - name: Change Directory
        run: |
          cd modrinth/fabric/$LATEST_VERSION
          ls
          
